### ISSUE TITLE
Service Providers are not properly propagated to children

### ISSUE THREAD

**Issue by LexManos** [McModLauncher/modlauncher#100]
The last argument to [defineModules](https://github.com/McModLauncher/modlauncher/blob/main/src/main/java/cpw/mods/modlauncher/ModuleLayerHandler.java#L76) is a function that looks up a module, and it's associated class loader.
This *should* return the correct classloader [for that specific module](https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/master/src/java.base/share/classes/java/lang/Module.java#L1083) which is required to [trigger bindToLayer](https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/master/src/java.base/share/classes/java/lang/Module.java#L1192), which is required for the [service catalog.](https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/master/src/java.base/share/classes/java/lang/ModuleLayer.java#L930)

Psudo of what the function should be:
`f -> newConf.modules.contains(d) ? classLoader : parent.stream().findFirst(l -> l.contains(f)).map(Layer::getClassLoader).orElse(classLoader)`
This causes service loaders for things like SLF4J to fail if they are first loaded from the MC context, which, in 1.18.2 they are.

**Comment by ichttt** [comment]
I tried to implement it in the way you described. Unfortunally, this did not work. This is because Module.java only calls the function for [modules of that classloader](https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/19fb8f93c59dfd791f62d41f332db9e306bc1422/src/java.base/share/classes/java/lang/Module.java#L1081), and not it's parents.
I currently also don't see any other way to get the log4j2 service info into the transforming class loader.

**Comment by cpw** [comment]
Hmmm. We probably need to assume control of log4j loading anyway.

**Comment by OrionDevelopment** [comment]
From testing myself, it looks like this is not directly possible with the current setup. As @ichttt already stated `Module.java` has a weird corner case here and I doubt we could modify its behavior enough to make it work. Optionally we could make the ServiceLoader use an adapted route through the classloader and combine all service specifications from the parent layers into one?
