### ISSUE TITLE
Classloader filtering of the javax package causes problems

### ISSUE THREAD

**Issue by Quantum64** [McModLauncher/modlauncher#27]
Delegating all javax package loadClass calls to the parent classloader is not a good idea. This is because some libraries bundle specific javax packages that are only available in the Java EE runtime into the library jars so that they run on Java SE as well. Specifically, I was trying to use the [Dagger 2](https://github.com/google/dagger) library with my mod which bundles the ``javax.inject`` package into the final jar. Since your classloader refuses to load javax classes, this will result in a ClassDefNotFound for Dagger 2 and any other dependency injection library.

d08c9b1300c65123d829c39a9907a22af05a297d

**Comment by cpw** [comment]
Interesting. I'll take a look. I explicitly didn't want transformers to operate on that namespace though.

**Comment by Quantum64** [comment]
Any update on this? Would it be possible to modify ``findClass`` so that it only transforms classes that do not match the filter instead of delegating all these classes to the parent?

**Comment by cpw** [comment]
No, quantum, that definitely would not work and would in fact break lots of things.

**Comment by Quantum64** [comment]
Just curious--what would that break specifically? The only difference I would expect from the current behavior is the loading of filtered packages from mod jars, and most mod jars don't have those packages in them anyway. The classes files that don't match the filter would still be transformed and the filtered packages would still not be transformed.

**Comment by cpw** [comment]
There's some special classes in javax, and it's possible to break a lot of shit about classloading if they're not pulled in in the right context. I'll look into limiting the package filtering a little tho.

**Comment by thecodewarrior** [comment]
I'm encountering a similar issue where I'm trying to bundle the LWJGL Yoga bindings because forge adds `org.lwjgl.*` into the filter. Relocating the package isn't an option in this case because doing so prevents the natives from linking.

Maybe instead of outright skipping the mod classloader the filter could instead reverse priority? If I'm reading the source right, modlauncher first looks at mod classloaders and then at the root classloader. Would it be possible to make the filter invert this so it loads from the root classloader if possible, then falls back to the mod classloader if the class wasn't found? That way all the MC classes will still be loaded without transformers, but classes in mods would still be available at runtime.

**Comment by Technici4n** [comment]
The package filter was removed starting from ML 9.

**Comment by Quantum64** [comment]
After 5 years I can finally sleep at night again
