### ISSUE TITLE
`ClassCastException` due to transformers that implement nonparameterized interfaces

### ISSUE THREAD

**Issue by auoeke** [McModLauncher/modlauncher#76]
[ModLauncher assumes that all generic interfaces of transformers are parameterized](https://github.com/cpw/modlauncher/blob/master/src/main/java/cpw/mods/modlauncher/TransformationServiceDecorator.java#L80). If it gets to a nonparameterized interface before `ITransformer` (or if the implemented `ITransformer` is nonparameterized), then the cast will fail and a `ClassCastException` will be thrown.

**Comment by cpw** [comment]
ITransformers are required to be parameterized by their ASM node type - ClassNode, MethodNode or FieldNode. Passing a non-parameterized type is going to fail downstream in a billion weird new ways, even if we fix this superficial input validation error, all that's going to change is that you're going to get a different crash report.

Note that the API for adding transformers does NOT specify a parameter because that broke a bunch of generic stuff further on. This might have been fixed since implementation in early J8 days.

**Comment by auoeke** [comment]
That's fine but I believe that the first case that I mentioned is valid: `class Transformer implements ITransformationService, ITransformer<ClassNode>` will not work; but `class Transformer implements ITransformer<ClassNode>, ITransformationService` will work.

**Comment by cpw** [comment]
That seems like a startlingly easy workaround... If you feel you could do that piece of code better without breaking everything, be my guest..
